var name =    "{Name:------@//*********Rahul*********//@---}";
var school =  "{School:----@//******Masai School*****//@---}";
var grade =   "{Grade: ----@//***********A+**********//@---}";
var section = "{Section: --@//***********B***********//@---}";
var rollno =  "{Roll no: --@//*******CAP07_051*******//@---}";
var HTML = "{HTML: -----@//***********95**********//@---}";
var CSS = "{CSS:-------@//***********91**********//@---}";
var JS = "{JS: -------@//***********85**********//@---}";
console.log(name);
console.log(school);
console.log(grade);
console.log(section);
console.log(rollno);
console.log(HTML);
console.log(CSS);
console.log(JS);
